version: '3.8'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-go-bot
    restart: unless-stopped
    environment:
      - ADMIN_PHONE_NUMBER=${ADMIN_PHONE_NUMBER:-}
      - SQLITE_DB=/app/data/whatsapp_bot.db
    volumes:
      # Persist WhatsApp session data
      - whatsapp_data:/app/data
      # Mount logs directory (optional)
      - ./logs:/app/logs
    # Enable interactive mode for QR code scanning
    stdin_open: true
    tty: true
    # For development, you might want to mount the source code
    # volumes:
    #   - .:/app
    #   - /app/go.mod
    #   - /app/go.sum

volumes:
  whatsapp_data:
    driver: local 